# release data downloaded to disk
data_root: /media/public_dataset2/ScanNet++_updated/data
scene_list_file: /media/Pluto/frank/3D-RS/third_party/ScanNetPP/iphone/downloaded_scene_list.txt

filter_scenes: []

# image type - iphone or dslr
image_type: iphone

no_log: true

# subsample images 
subsample_factor: 1
# downsample images and rasterize
image_downsample_factor: null

rasterout_dir: /media/public_dataset2/ScanNet++_updated/my_rasterize

limit_images: None

wandb_group: null
wandb_notes: null

batch_size: 1
limit_batches: null
skip_existing: true